version: '3.8'

services:
  image-host:
    build: .
    ports:
      - "8123:80"
    volumes:
      - /volume1/docker/大灰狼图床系统4.0源码/uploads:/var/www/html/uploads
      - /volume1/docker/大灰狼图床系统4.0源码:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped