version: '3.8'

services:
  image-host:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/var/www/html/uploads
      - .:/var/www/html
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped